### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by ja16005** [cyvius96/prototypical-network-pytorch#10]
Hi. 
I was trying out few shot on custom dataset, My custom data has 17 categories and 6 images per category.  created a class similar to MiniImageNet and used in it validation, i.e valset. But it is throwing me an error  in line 114 as
    loss = F.cross_entropy(logits, label)
  File "/home/search_env/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/search_env/lib/python3.6/site-packages/torch/nn/functional.py", line 1869, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (5) to match target batch_size (75).

Am I missing something? Kindly guide

**Comment by yinboc** [comment]
I am not sure what the exact problem is, replacing mini with custom dataset should work. It seems the batch_size of logits and label did not match, could you check their shape?

**Comment by ja16005** [comment]
yes, the shapes are different ..
Shape of logits torch.Size([5, 5])
Shape of label torch.Size([75])

Are there any constraints for the custom dataset for the code to run? Should I tweak any parameters accordingly?
I used the following parameters     
shot=5
query=15
train way=30
test way=5
I have used mini during training and custom dataset for validation which has 17 classes and 6 images per class.

**Comment by ja16005** [comment]
I referred to the paper and modified query=3 and shot=3 as per my custom training support. Now the code is working fine.

Thanks for the quick response! :)

**Comment by cyvius96** [comment]
I think logits and label should have the same batch dimention, what is the batch size you set? (5 or 75?) Since 'logits' is computed from 'data', you may check the shape of 'data'. Figuring out where the batch size gets wrong should help.

**Comment by yinboc** [comment]
I remember there should not be constraints for custom dataset. You may check the intermediate shapes to see what the exact problem is. The shape of logits should be [n_way * n_query, n_way], and shape of label should be [n_way * n_query].
