### ISSUE TITLE
How train with a new dataset

### ISSUE THREAD

**Issue by mohammad-saber** [cyvius96/prototypical-network-pytorch#12]
Thank you very much for sharing your code.

I want to train models with a dataset other than miniImageNet or Omniglot. Could you guide me how to arrange dataset (main folder , sub-folder), and how to train models on a new dataset?

Thanks a lot.

**Comment by cyvius96** [comment]
Hi. The format this miniImageNet is that, there are .csv files which specify the image list in each split, and an "image" folder that contains all the images, you may have a look on the "materials" folder after downloading the dataset.

Besides following the original format, you can also write a Pytorch dataset class for replacing mini_imagenet.py.

**Comment by yinboc** [comment]
Hi. The format of this miniImageNet is that, there are .csv files which specify the image list in each split, and an "image" folder that contains all the images, you may have a look at the "materials" folder after downloading the dataset.

Besides following the original format, you can also write a Pytorch dataset class for replacing mini_imagenet.py.
