### ISSUE TITLE
训练、测试曲线图training graph，testing graph

### ISSUE THREAD

**Issue by lwzhaojun** [cyvius96/prototypical-network-pytorch#14]
请问程序有没有训练测试的曲线图，trlog是训练曲线图吗？Does the program have a training test graph? Is trlog a training graph?

**Comment by yinboc** [comment]
You can use matplotlib to plot the curve from the records in trlog. (it is a dict and the file can be loaded by `torch.load('PATH/trlog')`)

**Comment by lwzhaojun** [comment]
thank you,this is useful.
