### ISSUE TITLE
Change step-size and max-epochs to get higher performance

### ISSUE THREAD

**Issue by csyanbin** [cyvius96/prototypical-network-pytorch#6]
Hello,

Thanks for this implementation.
Recently, I ran this repo with step-size=100 and max-epochs=2000 and got higher performance.

For 5way1shot train, I got 50.30% and for 5way5shot train I got 67.11%

**Comment by yinboc** [comment]
Hello,

Training for more epochs will get higher performance, but is relatively marginal while costing much more time.

Thanks for your observation and results.
