### ISSUE TITLE
Running on Google Colab

### ISSUE THREAD

**Issue by madiltalay** [cyvius96/prototypical-network-pytorch#8]
Dear Sir,
I am trying to run the code on google colab, but it seems to be slow. I wonder whether it is me being impatient or is it due to the way mini_imagenet.py is coded.
I wanted to ask which of the two options is faster?
1. accessing the images directly from folders 
2. converting the dataset into some other format like pickle/hdf5 etc
And if the second option is better, how do I convert to that?
Thanks

**Comment by yinboc** [comment]
Thanks for the question.

I am not sure since I didn't try other methods of reading. If you want a faster reading, maybe it could be tried to store data in memory (if it is sufficient), that is, to store images in data[i] instead of paths.
